###
POST   http://localhost:8000/api/auth/token/login/
Content-Type: application/json

{
  "password": "Vdgpz123",
  "email": "test1@yandex.ru"
}

###
POST http://localhost:8000/api/users/set_password/
Content-Type: application/json
Authorization: Token 6eb974c757af6cd78c7c31024ab5d9d29b4d9bfd

{
  "new_password": "Yanesb2022",
  "current_password": "yaensb_2022"
}

###
GET http://localhost:8000/api/users/

###
GET http://localhost:8000/api/users/1/
Authorization: Token 6eb974c757af6cd78c7c31024ab5d9d29b4d9bfd

###
GET http://localhost:8000/api/users/vasya/

###
GET http://localhost:8000/api/users/me/
Authorization: Token 6eb974c757af6cd78c7c31024ab5d9d29b4d9bfd

###
POST http://localhost:8000/api/users/
Content-Type: application/json

{
  "email": "test1@yandex.ru",
  "username": "test1",
  "first_name": "Test1",
  "last_name": "Test1",
  "password": "Vdgpz123"
}

###
GET http://localhost:8000/api/ingredients/